# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # ubuntu mongodb server
  config.vm.define "MongoDB-Server" do |mongodb|
    mongodb.vm.box = "ubuntu/xenial64"
    mongodb.vm.hostname = "Mongodb-Server"
	# connect on port 3306
	mongodb.vm.network "forwarded_port", guest: 27019, host: 27019
    mongodb.vm.network "private_network", ip: "172.42.42.42"
	
    mongodb.vm.provider "virtualbox" do |v|
      v.name = "Mongodb-Server"
      v.memory = 1024
      v.cpus = 1
    end
	
    mongodb.vm.provision "shell", path: "scripts/install.sh"
		
  end
end

