---
- name: Initialize Kubernetes
  shell: |
      kubeadm init --apiserver-advertise-address=172.42.42.100 --pod-network-cidr=10.244.0.0/16 >> /root/kubeinit.log 2>/dev/null

- name: Copy Kube admin config
  shell: |
      mkdir /home/vagrant/.kube
      cp /etc/kubernetes/admin.conf /home/vagrant/.kube/config
      chown -R vagrant:vagrant /home/vagrant/.kube

- name: Deploy flannel network
  shell: |
      su - vagrant -c "kubectl create -f /vagrant/kube-flannel.yaml"

- name: Deploy flannel network
  shell: |
      kubeadm token create --print-join-command > /joincluster.sh