apiVersion: ec2.aws.crossplane.io/v1beta1
kind: InternetGateway
metadata:
  name: sample-internetgateway
spec:
  forProvider:
    region: ap-south-1
    vpcIdRef:
      name: sample-vpc
  providerConfigRef:
    name: default
