# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # ubuntu mysql server
  config.vm.define "RabbitMQ-Server" do |rabbitmq|
    rabbitmq.vm.box = "ubuntu/xenial64"
    rabbitmq.vm.hostname = "RabbitMQ-Server"
	# connect on port 5672,15672,4369,25672
	rabbitmq.vm.network "forwarded_port", guest: 5672,  host: 5672
	rabbitmq.vm.network "forwarded_port", guest: 15672, host: 15672
	rabbitmq.vm.network "forwarded_port", guest: 4369,  host: 4369
	rabbitmq.vm.network "forwarded_port", guest: 25672, host: 25672
	
    rabbitmq.vm.network "private_network", ip: "172.42.42.42"
	
    rabbitmq.vm.provider "virtualbox" do |v|
      v.name = "RabbitMQ-Server"
      v.memory = 1024
      v.cpus = 1
    end
	
    rabbitmq.vm.provision "shell", path: "scripts/install.sh"
	
  end
end
