---
services:

  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    hostname: postgres
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    volumes: 
      - D:\IBM\DOCKER\pgdata:/var/lib/postgresql/data
      
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    restart: always
    depends_on:
      - postgres
    ports:
      - "15050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    # volumes:
      # - pgadmin-data:/var/lib/pgadmin
      # - ./scripts:/docker-entrypoint-initdb.d

# https://medium.com/@vishal.sharma./run-postgresql-and-pgadmin-using-docker-compose-34120618bcf9