# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure("2") do |config|

  config.ssh.insert_key = false
  
  # enable vagrant-cachier plugin if plugin is installed
  if Vagrant.has_plugin?("vagrant-cachier")
	  config.cache.auto_detect = false
	  config.cache.scope = :box
	  config.cache.enable :apt
	  config.cache.enable :apt_lists
	  config.cache.enable :composer
	  config.cache.enable :npm
  end

  # ubuntu_minikube single cluster kubernetes
  config.vm.define "minikube" do |minikube|
    minikube.vm.box = "ubuntu/xenial64"
    minikube.vm.hostname = "minikube"
#### accessing "172.42.42.100:8001" will access port 8443 on the guest machine.
	minikube.vm.network "forwarded_port", guest: 8443, host: 8001
    minikube.vm.network "private_network", ip: "172.42.42.100"
	
    minikube.vm.provider "virtualbox" do |v|
      v.name = "minikube"
      v.memory = 8192
      v.cpus = 4
    end
	
    minikube.vm.provision "shell", path: "scripts/docker.sh"
	minikube.vm.provision "shell", path: "scripts/aio.sh"
	
  end

end

