# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure("2") do |config|

  # ubuntu_minikube single cluster kubernetes
  config.vm.define "minikube" do |minikube|
    minikube.vm.box = "ubuntu/xenial64"
    minikube.vm.hostname = "minikube"
	minikube.vm.network "forwarded_port", guest: 8443, host: 8001
    minikube.vm.network "private_network", ip: "172.42.42.100"
	
    minikube.vm.provider "virtualbox" do |v|
      v.name = "minikube"
      v.memory = 4096
      v.cpus = 4
    end
	
    minikube.vm.provision "shell", path: "scripts/docker.sh"
	minikube.vm.provision "shell", path: "scripts/aio.sh"
	
  end

end

