# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # ubuntu redis server
  config.vm.define "Redis-Server" do |redis|
    redis.vm.box = "ubuntu/xenial64"
    redis.vm.hostname = "Redis-Server"
	redis.vm.network "forwarded_port", guest: 6379, host: 6379
    redis.vm.network "private_network", ip: "172.42.42.42"
	
    redis.vm.provider "virtualbox" do |v|
      v.name = "Redis-Server"
      v.memory = 1024
      v.cpus = 1
    end
	
    redis.vm.provision "shell", path: "scripts/install.sh"
		
  end
end

