apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo
spec:
  source:
    path: samples/bookinfo
    repoURL: https://github.com/istio/istio
    targetRevision: release-1.7
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true