# -*- mode: ruby -*-
# vi: set ft=ruby :

#ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure("2") do |config|

  config.ssh.insert_key = false
  
  # enable vagrant-cachier plugin if plugin is installed
  if Vagrant.has_plugin?("vagrant-cachier")
	  config.cache.auto_detect = true
	  config.cache.scope = :box
	  config.cache.enable :apt
	  config.cache.enable :apt_lists
	  config.cache.enable :composer
	  config.cache.enable :npm
  end
	  
  # ubuntu_minikube single cluster kubernetes
  config.vm.define "kube" do |kube|
    kube.vm.box = "ubuntu/xenial64"
    kube.vm.hostname = "kube"
	kube.vm.network "forwarded_port", guest: 8443, host: 8001
    kube.vm.network "private_network", ip: "172.42.42.100"
	
    kube.vm.provider "virtualbox" do |v|
      v.name = "kube"
      v.memory = 8192
      v.cpus = 4
    end
	kube.vm.provision "shell", inline: "export KUBELET_EXTRA_ARGS=--node-ip=172.42.42.100"
	kube.vm.provision "shell", path: "scripts/aio_docker-ce.sh"
  end

  NodeCount = 2
  # Kubernetes Worker Nodes
  (1..NodeCount).each do |i|
	config.vm.define "kworker#{i}" do |workernode|
	  workernode.vm.box = "ubuntu/xenial64"
	  workernode.vm.hostname = "kworker#{i}"
	  workernode.vm.network "private_network", ip: "172.42.42.10#{i}"
	  
	  workernode.vm.provider "virtualbox" do |v|
		v.name = "kworker#{i}"
		v.memory = 3072
		v.cpus = 3
	  end
	  workernode.vm.provision "shell", inline: "export KUBELET_EXTRA_ARGS=--node-ip='172.42.42.10#{i}'"
	  workernode.vm.provision "shell", path: "scripts/aio_worker.sh"
	end
  end

end

