---
- name: Add an apt signing key for Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add apt repository for stable version
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present

- name: Install docker and its dependecies
  apt: 
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - docker-ce=18.06.2~ce~3-0~ubuntu
  notify:
    - docker status

- name: Add vagrant user to docker group
  user:
    name: vagrant
    group: docker

- name: Copy daemon.json to /etc/docker
  copy:
    src: /vagrant/daemon.json
    dest: /etc/docker
    owner: root
    group: root
    mode: '0644'

- name: Restart Service Docker
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker
