apiVersion: ec2.aws.crossplane.io/v1beta1
kind: RouteTable
metadata:
  name: routetable
spec:
  forProvider:
    region: $(REGION)a
    routes:
      - destinationCidrBlock: 0.0.0.0/0
        gatewayIdRef:
          name: sample-internetgateway
    associations:
   - subnetIdRef:
          name: subnet-a
      - subnetIdRef:
          name: subnet-b
      - subnetIdRef:
          name: subnet-c
    vpcIdRef:
      name: sample-vpc
  providerConfigRef:
    name: default
