# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure("2") do |config|

  config.ssh.insert_key = false
  
  # enable vagrant-cachier plugin if plugin is installed
  if Vagrant.has_plugin?("vagrant-cachier")
	  config.cache.auto_detect = false
	  config.cache.scope = :box
	  config.cache.enable :apt
	  config.cache.enable :apt_lists
	  config.cache.enable :composer
	  config.cache.enable :npm
  end
  
  # ubuntu_microk8s single cluster kubernetes
  config.vm.define "microk8s" do |microk8s|
    microk8s.vm.box = "ubuntu/xenial64"
    microk8s.vm.hostname = "microk8s"
  	microk8s.vm.network "forwarded_port", guest: 443, host: 8001
    microk8s.vm.network "private_network", ip: "172.42.42.100"
	
    microk8s.vm.provider "virtualbox" do |v|
      v.name = "microk8s"
      v.memory = 8192
      v.cpus = 4
    end
	
    microk8s.vm.provision "shell", path: "scripts/snap.sh"
	
  end

end